export const KLED_GIT_REPOSITORY = "https://github.com/spectrumwebco/kled.io"

export const DEFAULT_STATIC_COMMAND_CONFIG = {
  streamResponse: false,
  debug: false,
} as const
/** placeholder for arbitrary additional flags */
export const WORKSPACE_COMMAND_ADDITIONAL_FLAGS_KEY = "additionalFlags"

export const KLED_BINARY = "bin/kled"
export const KCLUSTER_BINARY = "bin/kcluster"
export const KLEDSPACE_BINARY = "bin/kledspace"
export const KPOLICY_BINARY = "bin/kpolicy"

export const COMMAND_LIST = "list"
export const COMMAND_STATUS = "status"
export const COMMAND_UP = "up"
export const COMMAND_STOP = "stop"
export const COMMAND_BUILD = "build"
export const COMMAND_DELETE = "delete"
export const COMMAND_OPTIONS = "options"
export const COMMAND_SET_OPTIONS = "set-options"
export const COMMAND_USE = "use"
export const COMMAND_ADD = "add"
export const COMMAND_UPDATE = "update"
export const COMMAND_LOGIN = "login"

export const KLED_COMMAND_PROVIDER = "provider"
export const KLED_COMMAND_IDE = "ide"
export const KLED_COMMAND_PRO = "pro"
export const KLED_COMMAND_HELPER = "helper"
export const KLED_COMMAND_CONTEXT = "context"
export const KLED_COMMAND_IMPORT_WORKSPACE = "import-workspace"
export const KLED_COMMAND_GET_WORKSPACE_NAME = "get-workspace-name"
export const KLED_COMMAND_GET_WORKSPACE_UID = "get-workspace-uid"
export const KLED_COMMAND_GET_WORKSPACE_CONFIG = "get-workspace-config"
export const KLED_COMMAND_GET_PROVIDER_NAME = "get-provider-name"
export const KLED_COMMAND_GET_PRO_NAME = "get-pro-name"
export const KLED_COMMAND_CHECK_PROVIDER_UPDATE = "check-provider-update"
export const KLED_COMMAND_TROUBLESHOOT = "troubleshoot"

export const KCLUSTER_COMMAND_CREATE = "create"
export const KCLUSTER_COMMAND_CONNECT = "connect"
export const KCLUSTER_COMMAND_DISCONNECT = "disconnect"

export const KLEDSPACE_COMMAND_INIT = "init"
export const KLEDSPACE_COMMAND_DEPLOY = "deploy"
export const KLEDSPACE_COMMAND_PURGE = "purge"

export const KPOLICY_COMMAND_VALIDATE = "validate"
export const KPOLICY_COMMAND_APPLY = "apply"
export const KPOLICY_COMMAND_REMOVE = "remove"
export const FLAG_JSON_LOG_OUTPUT = "--log-output=json"
export const FLAG_JSON_OUTPUT = "--output=json"
export const FLAG_OPTION = "--option"
export const FLAG_FORCE = "--force"
export const FLAG_DEBUG = "--debug"
export const FLAG_NAME = "--name"
export const FLAG_ID = "--id"
export const FLAG_SOURCE = "--source"
export const FLAG_DRY = "--dry"
export const FLAG_TIMEOUT = "--timeout"
export const FLAG_LOGIN = "--login"
export const FLAG_HOST = "--host"
export const FLAG_PROJECT = "--project"

export const KLED_FLAG_FORCE_BUILD = "--force-build"
export const KLED_FLAG_RECREATE = "--recreate"
export const KLED_FLAG_RESET = "--reset"
export const KLED_FLAG_IDE = "--ide"
export const KLED_FLAG_PROVIDER = "--provider"
export const KLED_FLAG_PROVIDER_OPTION = "--provider-option"
export const KLED_FLAG_ACCESS_KEY = "--access-key"
export const KLED_FLAG_PREBUILD_REPOSITORY = "--prebuild-repository"
export const KLED_FLAG_USE = "--use"
export const KLED_FLAG_SINGLE_MACHINE = "--single-machine"
export const KLED_FLAG_RECONFIGURE = "--reconfigure"
export const KLED_FLAG_SKIP_REQUIRED = "--skip-required"
export const KLED_FLAG_DEVCONTAINER_PATH = "--devcontainer-path"
export const KLED_FLAG_WORKSPACE_ID = "--workspace-id"
export const KLED_FLAG_WORKSPACE_UID = "--workspace-uid"
export const KLED_FLAG_WORKSPACE_PROJECT = "--workspace-project"
export const KLED_FLAG_INSTANCE = "--instance"
export const KLED_FLAG_SKIP_PRO = "--skip-pro"
export const KLED_FLAG_DOTFILES = "--dotfiles"
export const KLED_FLAG_GIT_SIGNING_KEY = "--git-ssh-signing-key"
export const KLED_FLAG_FORCE_BROWSER = "--force-browser"

export const KCLUSTER_FLAG_NAMESPACE = "--namespace"
export const KCLUSTER_FLAG_CONTEXT = "--context"
export const KCLUSTER_FLAG_KUBECONFIG = "--kubeconfig"

export const KLEDSPACE_FLAG_ENV = "--env"
export const KLEDSPACE_FLAG_VALUES = "--values"
export const KLEDSPACE_FLAG_SET = "--set"

export const KPOLICY_FLAG_POLICY = "--policy"
export const KPOLICY_FLAG_NAMESPACE = "--namespace"
export const KPOLICY_FLAG_ALL_NAMESPACES = "--all-namespaces"

export const KLED_UI_ENV_VAR = "KLED_UI"
export const API_KEY_ENV_VAR = "KLED_API_KEY"
export const API_BASE_URL_ENV_VAR = "KLED_API_BASE_URL"
