apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-vault-plugin
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/spectrumwebco/kled.io.git
    targetRevision: HEAD
    path: k8s/argo/vault-plugin
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
