name: Build and Release CLI Tools

on:
  push:
    branches: [main]
    tags: ['v*']
  workflow_dispatch:

jobs:
  build:
    name: Build CLI Tools
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            platform: linux
            arch: amd64
            artifact_name: kled-linux-amd64
            asset_name: kled-linux-amd64
          - os: macos-latest
            platform: darwin
            arch: amd64
            artifact_name: kled-darwin-amd64
            asset_name: kled-darwin-amd64
          - os: windows-latest
            platform: windows
            arch: amd64
            artifact_name: kled-windows-amd64.exe
            asset_name: kled-windows-amd64.exe

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build unified CLI binary
        run: |
          mkdir -p bin
          GOOS=${{ matrix.platform }} GOARCH=${{ matrix.arch }} go build -o bin/${{ matrix.artifact_name }} ./cli/unified

      - name: Create symlinks for individual tools (Linux/macOS)
        if: matrix.platform != 'windows'
        run: |
          ln -sf ${{ matrix.artifact_name }} bin/kled
          ln -sf ${{ matrix.artifact_name }} bin/kcluster
          ln -sf ${{ matrix.artifact_name }} bin/kledspace
          ln -sf ${{ matrix.artifact_name }} bin/kpolicy

      - name: Create batch files for Windows
        if: matrix.platform == 'windows'
        run: |
          echo "@echo off" > bin/kled.bat
          echo "kled-windows-amd64.exe kled %*" >> bin/kled.bat
          echo "@echo off" > bin/kcluster.bat
          echo "kled-windows-amd64.exe kcluster %*" >> bin/kcluster.bat
          echo "@echo off" > bin/kledspace.bat
          echo "kled-windows-amd64.exe kledspace %*" >> bin/kledspace.bat
          echo "@echo off" > bin/kpolicy.bat
          echo "kled-windows-amd64.exe kpolicy %*" >> bin/kpolicy.bat

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.asset_name }}
          path: bin/

  release:
    name: Create Release
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            kled-linux-amd64/*
            kled-darwin-amd64/*
            kled-windows-amd64.exe/*
          draft: false
          prerelease: false
